### ISSUE TITLE
How to open the modal?

### ISSUE THREAD

**Issue by ImHicham** [filaraujo/akyral-modal#17]
Was just playing around with the modals and couldn't get them to work. 

I tried it like so:

```javascript
document.querySelector("akyral-modal").show();
```

And from the console I got this:

akyral-modal :: You can't interact with this element directly

Is this the intended behavour? I read the docs again and couldn't figure this out.

**Comment by filaraujo** [comment]
you should be able to target the akyral-modal that you created in the dom.

html
```html
<akyral-modal id="modal">
  contents.....
</akyral-modal>
```

script
```js
var modal = document.querySelector('#modal').show();
```
